//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FuzzyLogicModel", "FK__FuzzyMode__UserI__060DEAE8", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FuzzyLogicWebService.Models.User), "FuzzyModels", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FuzzyLogicWebService.Models.FuzzyModel), true)]
[assembly: EdmRelationshipAttribute("FuzzyLogicModel", "FK__FuzzyRule__Model__145C0A3F", "FuzzyModels", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FuzzyLogicWebService.Models.FuzzyModel), "FuzzyRules", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FuzzyLogicWebService.Models.FuzzyRule), true)]
[assembly: EdmRelationshipAttribute("FuzzyLogicModel", "FK__FuzzyVari__Model__0AD2A005", "FuzzyModels", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FuzzyLogicWebService.Models.FuzzyModel), "FuzzyVariables", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FuzzyLogicWebService.Models.FuzzyVariable), true)]
[assembly: EdmRelationshipAttribute("FuzzyLogicModel", "FK__Membershi__Varia__0F975522", "FuzzyVariables", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FuzzyLogicWebService.Models.FuzzyVariable), "MembershipFunctions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FuzzyLogicWebService.Models.MembershipFunction), true)]

#endregion

namespace FuzzyLogicWebService.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FuzzyLogicDBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FuzzyLogicDBContext object using the connection string found in the 'FuzzyLogicDBContext' section of the application configuration file.
        /// </summary>
        public FuzzyLogicDBContext() : base("name=FuzzyLogicDBContext", "FuzzyLogicDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FuzzyLogicDBContext object.
        /// </summary>
        public FuzzyLogicDBContext(string connectionString) : base(connectionString, "FuzzyLogicDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FuzzyLogicDBContext object.
        /// </summary>
        public FuzzyLogicDBContext(EntityConnection connection) : base(connection, "FuzzyLogicDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FuzzyModel> FuzzyModels
        {
            get
            {
                if ((_FuzzyModels == null))
                {
                    _FuzzyModels = base.CreateObjectSet<FuzzyModel>("FuzzyModels");
                }
                return _FuzzyModels;
            }
        }
        private ObjectSet<FuzzyModel> _FuzzyModels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FuzzyRule> FuzzyRules
        {
            get
            {
                if ((_FuzzyRules == null))
                {
                    _FuzzyRules = base.CreateObjectSet<FuzzyRule>("FuzzyRules");
                }
                return _FuzzyRules;
            }
        }
        private ObjectSet<FuzzyRule> _FuzzyRules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FuzzyVariable> FuzzyVariables
        {
            get
            {
                if ((_FuzzyVariables == null))
                {
                    _FuzzyVariables = base.CreateObjectSet<FuzzyVariable>("FuzzyVariables");
                }
                return _FuzzyVariables;
            }
        }
        private ObjectSet<FuzzyVariable> _FuzzyVariables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MembershipFunction> MembershipFunctions
        {
            get
            {
                if ((_MembershipFunctions == null))
                {
                    _MembershipFunctions = base.CreateObjectSet<MembershipFunction>("MembershipFunctions");
                }
                return _MembershipFunctions;
            }
        }
        private ObjectSet<MembershipFunction> _MembershipFunctions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FuzzyModels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuzzyModels(FuzzyModel fuzzyModel)
        {
            base.AddObject("FuzzyModels", fuzzyModel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FuzzyRules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuzzyRules(FuzzyRule fuzzyRule)
        {
            base.AddObject("FuzzyRules", fuzzyRule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FuzzyVariables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuzzyVariables(FuzzyVariable fuzzyVariable)
        {
            base.AddObject("FuzzyVariables", fuzzyVariable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MembershipFunctions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembershipFunctions(MembershipFunction membershipFunction)
        {
            base.AddObject("MembershipFunctions", membershipFunction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FuzzyLogicModel", Name="FuzzyModel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FuzzyModel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FuzzyModel object.
        /// </summary>
        /// <param name="modelID">Initial value of the ModelID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="inputsNumber">Initial value of the InputsNumber property.</param>
        /// <param name="outputsNumber">Initial value of the OutputsNumber property.</param>
        /// <param name="rulesNumber">Initial value of the RulesNumber property.</param>
        public static FuzzyModel CreateFuzzyModel(global::System.Int32 modelID, global::System.Int32 userID, global::System.String name, global::System.Int32 inputsNumber, global::System.Int32 outputsNumber, global::System.Int32 rulesNumber)
        {
            FuzzyModel fuzzyModel = new FuzzyModel();
            fuzzyModel.ModelID = modelID;
            fuzzyModel.UserID = userID;
            fuzzyModel.Name = name;
            fuzzyModel.InputsNumber = inputsNumber;
            fuzzyModel.OutputsNumber = outputsNumber;
            fuzzyModel.RulesNumber = rulesNumber;
            return fuzzyModel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelID
        {
            get
            {
                return _ModelID;
            }
            set
            {
                if (_ModelID != value)
                {
                    OnModelIDChanging(value);
                    ReportPropertyChanging("ModelID");
                    _ModelID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModelID");
                    OnModelIDChanged();
                }
            }
        }
        private global::System.Int32 _ModelID;
        partial void OnModelIDChanging(global::System.Int32 value);
        partial void OnModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InputsNumber
        {
            get
            {
                return _InputsNumber;
            }
            set
            {
                OnInputsNumberChanging(value);
                ReportPropertyChanging("InputsNumber");
                _InputsNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InputsNumber");
                OnInputsNumberChanged();
            }
        }
        private global::System.Int32 _InputsNumber;
        partial void OnInputsNumberChanging(global::System.Int32 value);
        partial void OnInputsNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OutputsNumber
        {
            get
            {
                return _OutputsNumber;
            }
            set
            {
                OnOutputsNumberChanging(value);
                ReportPropertyChanging("OutputsNumber");
                _OutputsNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OutputsNumber");
                OnOutputsNumberChanged();
            }
        }
        private global::System.Int32 _OutputsNumber;
        partial void OnOutputsNumberChanging(global::System.Int32 value);
        partial void OnOutputsNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RulesNumber
        {
            get
            {
                return _RulesNumber;
            }
            set
            {
                OnRulesNumberChanging(value);
                ReportPropertyChanging("RulesNumber");
                _RulesNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RulesNumber");
                OnRulesNumberChanged();
            }
        }
        private global::System.Int32 _RulesNumber;
        partial void OnRulesNumberChanging(global::System.Int32 value);
        partial void OnRulesNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyMode__UserI__060DEAE8", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyRule__Model__145C0A3F", "FuzzyRules")]
        public EntityCollection<FuzzyRule> FuzzyRules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FuzzyRule>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyRules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FuzzyRule>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyRules", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyVari__Model__0AD2A005", "FuzzyVariables")]
        public EntityCollection<FuzzyVariable> FuzzyVariables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FuzzyVariable>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyVariables");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FuzzyVariable>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyVariables", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FuzzyLogicModel", Name="FuzzyRule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FuzzyRule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FuzzyRule object.
        /// </summary>
        /// <param name="ruleID">Initial value of the RuleID property.</param>
        /// <param name="modelID">Initial value of the ModelID property.</param>
        /// <param name="ruleContent">Initial value of the RuleContent property.</param>
        public static FuzzyRule CreateFuzzyRule(global::System.Int32 ruleID, global::System.Int32 modelID, global::System.String ruleContent)
        {
            FuzzyRule fuzzyRule = new FuzzyRule();
            fuzzyRule.RuleID = ruleID;
            fuzzyRule.ModelID = modelID;
            fuzzyRule.RuleContent = ruleContent;
            return fuzzyRule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RuleID
        {
            get
            {
                return _RuleID;
            }
            set
            {
                if (_RuleID != value)
                {
                    OnRuleIDChanging(value);
                    ReportPropertyChanging("RuleID");
                    _RuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RuleID");
                    OnRuleIDChanged();
                }
            }
        }
        private global::System.Int32 _RuleID;
        partial void OnRuleIDChanging(global::System.Int32 value);
        partial void OnRuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelID
        {
            get
            {
                return _ModelID;
            }
            set
            {
                OnModelIDChanging(value);
                ReportPropertyChanging("ModelID");
                _ModelID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelID");
                OnModelIDChanged();
            }
        }
        private global::System.Int32 _ModelID;
        partial void OnModelIDChanging(global::System.Int32 value);
        partial void OnModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleContent
        {
            get
            {
                return _RuleContent;
            }
            set
            {
                OnRuleContentChanging(value);
                ReportPropertyChanging("RuleContent");
                _RuleContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RuleContent");
                OnRuleContentChanged();
            }
        }
        private global::System.String _RuleContent;
        partial void OnRuleContentChanging(global::System.String value);
        partial void OnRuleContentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyRule__Model__145C0A3F", "FuzzyModels")]
        public FuzzyModel FuzzyModel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyModels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyModels").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FuzzyModel> FuzzyModelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyModels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyRule__Model__145C0A3F", "FuzzyModels", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FuzzyLogicModel", Name="FuzzyVariable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FuzzyVariable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FuzzyVariable object.
        /// </summary>
        /// <param name="variableID">Initial value of the VariableID property.</param>
        /// <param name="modelID">Initial value of the ModelID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="minValue">Initial value of the MinValue property.</param>
        /// <param name="maxValue">Initial value of the MaxValue property.</param>
        /// <param name="numberOfMembFunc">Initial value of the NumberOfMembFunc property.</param>
        /// <param name="variableType">Initial value of the VariableType property.</param>
        public static FuzzyVariable CreateFuzzyVariable(global::System.Int32 variableID, global::System.Int32 modelID, global::System.String name, global::System.Double minValue, global::System.Double maxValue, global::System.Int32 numberOfMembFunc, global::System.Int32 variableType)
        {
            FuzzyVariable fuzzyVariable = new FuzzyVariable();
            fuzzyVariable.VariableID = variableID;
            fuzzyVariable.ModelID = modelID;
            fuzzyVariable.Name = name;
            fuzzyVariable.MinValue = minValue;
            fuzzyVariable.MaxValue = maxValue;
            fuzzyVariable.NumberOfMembFunc = numberOfMembFunc;
            fuzzyVariable.VariableType = variableType;
            return fuzzyVariable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VariableID
        {
            get
            {
                return _VariableID;
            }
            set
            {
                if (_VariableID != value)
                {
                    OnVariableIDChanging(value);
                    ReportPropertyChanging("VariableID");
                    _VariableID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VariableID");
                    OnVariableIDChanged();
                }
            }
        }
        private global::System.Int32 _VariableID;
        partial void OnVariableIDChanging(global::System.Int32 value);
        partial void OnVariableIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelID
        {
            get
            {
                return _ModelID;
            }
            set
            {
                OnModelIDChanging(value);
                ReportPropertyChanging("ModelID");
                _ModelID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelID");
                OnModelIDChanged();
            }
        }
        private global::System.Int32 _ModelID;
        partial void OnModelIDChanging(global::System.Int32 value);
        partial void OnModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MinValue
        {
            get
            {
                return _MinValue;
            }
            set
            {
                OnMinValueChanging(value);
                ReportPropertyChanging("MinValue");
                _MinValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinValue");
                OnMinValueChanged();
            }
        }
        private global::System.Double _MinValue;
        partial void OnMinValueChanging(global::System.Double value);
        partial void OnMinValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MaxValue
        {
            get
            {
                return _MaxValue;
            }
            set
            {
                OnMaxValueChanging(value);
                ReportPropertyChanging("MaxValue");
                _MaxValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxValue");
                OnMaxValueChanged();
            }
        }
        private global::System.Double _MaxValue;
        partial void OnMaxValueChanging(global::System.Double value);
        partial void OnMaxValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfMembFunc
        {
            get
            {
                return _NumberOfMembFunc;
            }
            set
            {
                OnNumberOfMembFuncChanging(value);
                ReportPropertyChanging("NumberOfMembFunc");
                _NumberOfMembFunc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfMembFunc");
                OnNumberOfMembFuncChanged();
            }
        }
        private global::System.Int32 _NumberOfMembFunc;
        partial void OnNumberOfMembFuncChanging(global::System.Int32 value);
        partial void OnNumberOfMembFuncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VariableType
        {
            get
            {
                return _VariableType;
            }
            set
            {
                OnVariableTypeChanging(value);
                ReportPropertyChanging("VariableType");
                _VariableType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VariableType");
                OnVariableTypeChanged();
            }
        }
        private global::System.Int32 _VariableType;
        partial void OnVariableTypeChanging(global::System.Int32 value);
        partial void OnVariableTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyVari__Model__0AD2A005", "FuzzyModels")]
        public FuzzyModel FuzzyModel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyModels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyModels").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FuzzyModel> FuzzyModelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyModels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FuzzyModel>("FuzzyLogicModel.FK__FuzzyVari__Model__0AD2A005", "FuzzyModels", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__Membershi__Varia__0F975522", "MembershipFunctions")]
        public EntityCollection<MembershipFunction> MembershipFunctions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MembershipFunction>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "MembershipFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MembershipFunction>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "MembershipFunctions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FuzzyLogicModel", Name="MembershipFunction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MembershipFunction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MembershipFunction object.
        /// </summary>
        /// <param name="functionID">Initial value of the FunctionID property.</param>
        /// <param name="variableID">Initial value of the VariableID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="firstValue">Initial value of the FirstValue property.</param>
        /// <param name="secondValue">Initial value of the SecondValue property.</param>
        /// <param name="thirdValue">Initial value of the ThirdValue property.</param>
        public static MembershipFunction CreateMembershipFunction(global::System.Int32 functionID, global::System.Int32 variableID, global::System.String name, global::System.Double firstValue, global::System.Double secondValue, global::System.Double thirdValue)
        {
            MembershipFunction membershipFunction = new MembershipFunction();
            membershipFunction.FunctionID = functionID;
            membershipFunction.VariableID = variableID;
            membershipFunction.Name = name;
            membershipFunction.FirstValue = firstValue;
            membershipFunction.SecondValue = secondValue;
            membershipFunction.ThirdValue = thirdValue;
            return membershipFunction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FunctionID
        {
            get
            {
                return _FunctionID;
            }
            set
            {
                if (_FunctionID != value)
                {
                    OnFunctionIDChanging(value);
                    ReportPropertyChanging("FunctionID");
                    _FunctionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FunctionID");
                    OnFunctionIDChanged();
                }
            }
        }
        private global::System.Int32 _FunctionID;
        partial void OnFunctionIDChanging(global::System.Int32 value);
        partial void OnFunctionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VariableID
        {
            get
            {
                return _VariableID;
            }
            set
            {
                OnVariableIDChanging(value);
                ReportPropertyChanging("VariableID");
                _VariableID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VariableID");
                OnVariableIDChanged();
            }
        }
        private global::System.Int32 _VariableID;
        partial void OnVariableIDChanging(global::System.Int32 value);
        partial void OnVariableIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double FirstValue
        {
            get
            {
                return _FirstValue;
            }
            set
            {
                OnFirstValueChanging(value);
                ReportPropertyChanging("FirstValue");
                _FirstValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstValue");
                OnFirstValueChanged();
            }
        }
        private global::System.Double _FirstValue;
        partial void OnFirstValueChanging(global::System.Double value);
        partial void OnFirstValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SecondValue
        {
            get
            {
                return _SecondValue;
            }
            set
            {
                OnSecondValueChanging(value);
                ReportPropertyChanging("SecondValue");
                _SecondValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SecondValue");
                OnSecondValueChanged();
            }
        }
        private global::System.Double _SecondValue;
        partial void OnSecondValueChanging(global::System.Double value);
        partial void OnSecondValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ThirdValue
        {
            get
            {
                return _ThirdValue;
            }
            set
            {
                OnThirdValueChanging(value);
                ReportPropertyChanging("ThirdValue");
                _ThirdValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThirdValue");
                OnThirdValueChanged();
            }
        }
        private global::System.Double _ThirdValue;
        partial void OnThirdValueChanging(global::System.Double value);
        partial void OnThirdValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> FourthValue
        {
            get
            {
                return _FourthValue;
            }
            set
            {
                OnFourthValueChanging(value);
                ReportPropertyChanging("FourthValue");
                _FourthValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FourthValue");
                OnFourthValueChanged();
            }
        }
        private Nullable<global::System.Double> _FourthValue;
        partial void OnFourthValueChanging(Nullable<global::System.Double> value);
        partial void OnFourthValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__Membershi__Varia__0F975522", "FuzzyVariables")]
        public FuzzyVariable FuzzyVariable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyVariable>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "FuzzyVariables").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyVariable>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "FuzzyVariables").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FuzzyVariable> FuzzyVariableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FuzzyVariable>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "FuzzyVariables");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FuzzyVariable>("FuzzyLogicModel.FK__Membershi__Varia__0F975522", "FuzzyVariables", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FuzzyLogicModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String name)
        {
            User user = new User();
            user.UserID = userID;
            user.Name = name;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FuzzyLogicModel", "FK__FuzzyMode__UserI__060DEAE8", "FuzzyModels")]
        public EntityCollection<FuzzyModel> FuzzyModels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FuzzyModel>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "FuzzyModels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FuzzyModel>("FuzzyLogicModel.FK__FuzzyMode__UserI__060DEAE8", "FuzzyModels", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
