//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kolejny punkt.
        /// </summary>
        public static string AddMajorPoint {
            get {
                return ResourceManager.GetString("AddMajorPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zmienne.
        /// </summary>
        public static string AddVariables {
            get {
                return ResourceManager.GetString("AddVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zacznij obliczenia.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdefiniuj funkcje przynależności.
        /// </summary>
        public static string DefineMF {
            get {
                return ResourceManager.GetString("DefineMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj opis.
        /// </summary>
        public static string DescriptionErrorMsg {
            get {
                return ResourceManager.GetString("DescriptionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krótki opis.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły modelu: .
        /// </summary>
        public static string DetailsOfModel {
            get {
                return ResourceManager.GetString("DetailsOfModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź zmiany.
        /// </summary>
        public static string EditModel {
            get {
                return ResourceManager.GetString("EditModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza charakterystyczna wartość.
        /// </summary>
        public static string FirstValue {
            get {
                return ResourceManager.GetString("FirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj pierwszą charakterystyczną wartość.
        /// </summary>
        public static string FirstValueErrorMsg {
            get {
                return ResourceManager.GetString("FirstValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czwarta charakterystyczna wartość.
        /// </summary>
        public static string FourthValue {
            get {
                return ResourceManager.GetString("FourthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj:.
        /// </summary>
        public static string FunctionType {
            get {
                return ResourceManager.GetString("FunctionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa zmiennej:.
        /// </summary>
        public static string FVariableName {
            get {
                return ResourceManager.GetString("FVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę zmiennej.
        /// </summary>
        public static string FVariableNameErrorMsg {
            get {
                return ResourceManager.GetString("FVariableNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wejść:.
        /// </summary>
        public static string InputsNumber {
            get {
                return ResourceManager.GetString("InputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę wejść.
        /// </summary>
        public static string InputsNumberErrorMsg {
            get {
                return ResourceManager.GetString("InputsNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wartości wejściowe.
        /// </summary>
        public static string InsertInputValues {
            get {
                return ResourceManager.GetString("InsertInputValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna wartość zmiennej:.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj maksymalną wartość zmiennej.
        /// </summary>
        public static string MaxValueErrorMsg {
            get {
                return ResourceManager.GetString("MaxValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string MembershipFunctionName {
            get {
                return ResourceManager.GetString("MembershipFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę funkcji przynależności.
        /// </summary>
        public static string MembershipFunctionNameErrorMsg {
            get {
                return ResourceManager.GetString("MembershipFunctionNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna wartość zmiennej:.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj minimalną wartość zmiennej.
        /// </summary>
        public static string MinValueErrorMsg {
            get {
                return ResourceManager.GetString("MinValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba funkcji przynależności:.
        /// </summary>
        public static string NumberOfMembFunc {
            get {
                return ResourceManager.GetString("NumberOfMembFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę funkcji przynależności.
        /// </summary>
        public static string NumberOfMembFuncErrorMsg {
            get {
                return ResourceManager.GetString("NumberOfMembFuncErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wyjść:.
        /// </summary>
        public static string OutputsNumber {
            get {
                return ResourceManager.GetString("OutputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbe wyjść.
        /// </summary>
        public static string OutputsNumberErrorMsg {
            get {
                return ResourceManager.GetString("OutputsNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść reguły.
        /// </summary>
        public static string RuleContent {
            get {
                return ResourceManager.GetString("RuleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reguła jest wymagana.
        /// </summary>
        public static string RuleContentErrorMsg {
            get {
                return ResourceManager.GetString("RuleContentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba reguł:.
        /// </summary>
        public static string RulesNumber {
            get {
                return ResourceManager.GetString("RulesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę reguł.
        /// </summary>
        public static string RulesNumberErrorMsg {
            get {
                return ResourceManager.GetString("RulesNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga charakterystyczna wartość.
        /// </summary>
        public static string SecondValue {
            get {
                return ResourceManager.GetString("SecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj drugą charakterystyczną wartość.
        /// </summary>
        public static string SecondValueErrorMsg {
            get {
                return ResourceManager.GetString("SecondValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz szczegóły.
        /// </summary>
        public static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa modelu domyslna.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jest wymagana.
        /// </summary>
        public static string SystemNameErrorMsg {
            get {
                return ResourceManager.GetString("SystemNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trzecia charakterystyczna wartość.
        /// </summary>
        public static string ThirdValue {
            get {
                return ResourceManager.GetString("ThirdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj trzecią charakterystyczną wartość.
        /// </summary>
        public static string ThirdValueErrorMsg {
            get {
                return ResourceManager.GetString("ThirdValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz rodzaj funkcji przynależności.
        /// </summary>
        public static string TypeErrorMsg {
            get {
                return ResourceManager.GetString("TypeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę użytkownika.
        /// </summary>
        public static string UserNameErrorMsg {
            get {
                return ResourceManager.GetString("UserNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj hasło.
        /// </summary>
        public static string UserPasswordErrorMsg {
            get {
                return ResourceManager.GetString("UserPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj tego modelu.
        /// </summary>
        public static string UseThisModel {
            get {
                return ResourceManager.GetString("UseThisModel", resourceCulture);
            }
        }
    }
}
