//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logice rozmytej.
        /// </summary>
        public static string AboutFuzzyLogicTab {
            get {
                return ResourceManager.GetString("AboutFuzzyLogicTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zmienne wejściowe.
        /// </summary>
        public static string AddInputVariables {
            get {
                return ResourceManager.GetString("AddInputVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kolejny punkt.
        /// </summary>
        public static string AddMajorPoint {
            get {
                return ResourceManager.GetString("AddMajorPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj funkcje przynależności.
        /// </summary>
        public static string AddMembershipFunc {
            get {
                return ResourceManager.GetString("AddMembershipFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zmienną wyjściową.
        /// </summary>
        public static string AddOutputVariable {
            get {
                return ResourceManager.GetString("AddOutputVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj reguły.
        /// </summary>
        public static string AddRules {
            get {
                return ResourceManager.GetString("AddRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zmienne.
        /// </summary>
        public static string AddVariables {
            get {
                return ResourceManager.GetString("AddVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzyj modele.
        /// </summary>
        public static string BrowseModelsTab {
            get {
                return ResourceManager.GetString("BrowseModelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zacznij obliczenia.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obliczenia.
        /// </summary>
        public static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj model.
        /// </summary>
        public static string CopyModel {
            get {
                return ResourceManager.GetString("CopyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończony.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdefiniuj nowy model.
        /// </summary>
        public static string CreateMamdaniModel {
            get {
                return ResourceManager.GetString("CreateMamdaniModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz model.
        /// </summary>
        public static string CreateModelTab {
            get {
                return ResourceManager.GetString("CreateModelTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdefiniuj funkcje przynależności.
        /// </summary>
        public static string DefineMF {
            get {
                return ResourceManager.GetString("DefineMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń model.
        /// </summary>
        public static string DeleteModel {
            get {
                return ResourceManager.GetString("DeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj opis.
        /// </summary>
        public static string DescriptionErrorMsg {
            get {
                return ResourceManager.GetString("DescriptionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krótki opis.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły modelu.
        /// </summary>
        public static string DetailsOfModel {
            get {
                return ResourceManager.GetString("DetailsOfModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź zmiany.
        /// </summary>
        public static string EditModel {
            get {
                return ResourceManager.GetString("EditModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź login i hasło..
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwszy punkt.
        /// </summary>
        public static string FirstValue {
            get {
                return ResourceManager.GetString("FirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj pierwszą charakterystyczną wartość.
        /// </summary>
        public static string FirstValueErrorMsg {
            get {
                return ResourceManager.GetString("FirstValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czwarty punkt.
        /// </summary>
        public static string FourthValue {
            get {
                return ResourceManager.GetString("FourthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string FunctionType {
            get {
                return ResourceManager.GetString("FunctionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logika rozmyta.
        /// </summary>
        public static string FuzzyLogicTitle {
            get {
                return ResourceManager.GetString("FuzzyLogicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa zmiennej.
        /// </summary>
        public static string FVariableName {
            get {
                return ResourceManager.GetString("FVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę zmiennej.
        /// </summary>
        public static string FVariableNameErrorMsg {
            get {
                return ResourceManager.GetString("FVariableNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj plik .fis.
        /// </summary>
        public static string GenerateFisFile {
            get {
                return ResourceManager.GetString("GenerateFisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nową nazwę.
        /// </summary>
        public static string GiveNewName {
            get {
                return ResourceManager.GetString("GiveNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak korzystać.
        /// </summary>
        public static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne dane. .
        /// </summary>
        public static string IncorrectLoginErrorMsg {
            get {
                return ResourceManager.GetString("IncorrectLoginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wejście.
        /// </summary>
        public static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wejść.
        /// </summary>
        public static string InputsNumber {
            get {
                return ResourceManager.GetString("InputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę wejść.
        /// </summary>
        public static string InputsNumberErrorMsg {
            get {
                return ResourceManager.GetString("InputsNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wartości wejściowe.
        /// </summary>
        public static string InsertInputValues {
            get {
                return ResourceManager.GetString("InsertInputValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista modeli.
        /// </summary>
        public static string ListOfModels {
            get {
                return ResourceManager.GetString("ListOfModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany login juz istnieje. Proszę wybierz inny..
        /// </summary>
        public static string LoginOccupiedErrorMessage {
            get {
                return ResourceManager.GetString("LoginOccupiedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna wartość zmiennej.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj maksymalną wartość zmiennej.
        /// </summary>
        public static string MaxValueErrorMsg {
            get {
                return ResourceManager.GetString("MaxValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string MembershipFunctionName {
            get {
                return ResourceManager.GetString("MembershipFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę funkcji przynależności.
        /// </summary>
        public static string MembershipFunctionNameErrorMsg {
            get {
                return ResourceManager.GetString("MembershipFunctionNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna wartość zmiennej:.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj minimalną wartość zmiennej.
        /// </summary>
        public static string MinValueErrorMsg {
            get {
                return ResourceManager.GetString("MinValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutaj powinien być wykres przedstawiający .
        /// </summary>
        public static string MissingGraphErrMsg {
            get {
                return ResourceManager.GetString("MissingGraphErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje zmiennych wejściowych.
        /// </summary>
        public static string MissingInputs {
            get {
                return ResourceManager.GetString("MissingInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje funkcji przynależności.
        /// </summary>
        public static string MissingMembFunctions {
            get {
                return ResourceManager.GetString("MissingMembFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje zmiennej wejściowej.
        /// </summary>
        public static string MissingOutputs {
            get {
                return ResourceManager.GetString("MissingOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje reguł.
        /// </summary>
        public static string MissingRules {
            get {
                return ResourceManager.GetString("MissingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ModelStatus {
            get {
                return ResourceManager.GetString("ModelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOWY .
        /// </summary>
        public static string NewModelName {
            get {
                return ResourceManager.GetString("NewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie stworzyłeś jeszcze żadnych modeli. Możesz to zrobić .
        /// </summary>
        public static string NoModelsMsg {
            get {
                return ResourceManager.GetString("NoModelsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba funkcji przynależności.
        /// </summary>
        public static string NumberOfMembFunc {
            get {
                return ResourceManager.GetString("NumberOfMembFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę funkcji przynależności.
        /// </summary>
        public static string NumberOfMembFuncErrorMsg {
            get {
                return ResourceManager.GetString("NumberOfMembFuncErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        public static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wyjść.
        /// </summary>
        public static string OutputsNumber {
            get {
                return ResourceManager.GetString("OutputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę wyjść.
        /// </summary>
        public static string OutputsNumberErrorMsg {
            get {
                return ResourceManager.GetString("OutputsNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeśli nie masz konta..
        /// </summary>
        public static string RegisterCondition {
            get {
                return ResourceManager.GetString("RegisterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dane do rejestracji.
        /// </summary>
        public static string RegisterData {
            get {
                return ResourceManager.GetString("RegisterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można stworzyć konta. Dane są nieprawidłowe..
        /// </summary>
        public static string RegisterErrorMessage {
            get {
                return ResourceManager.GetString("RegisterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wymagane dane by móc sie zarejestrować.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść reguły.
        /// </summary>
        public static string RuleContent {
            get {
                return ResourceManager.GetString("RuleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reguła jest wymagana.
        /// </summary>
        public static string RuleContentErrorMsg {
            get {
                return ResourceManager.GetString("RuleContentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reguły.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba reguł.
        /// </summary>
        public static string RulesNumber {
            get {
                return ResourceManager.GetString("RulesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę reguł.
        /// </summary>
        public static string RulesNumberErrorMsg {
            get {
                return ResourceManager.GetString("RulesNumberErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugi punkt.
        /// </summary>
        public static string SecondValue {
            get {
                return ResourceManager.GetString("SecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj drugą charakterystyczną wartość.
        /// </summary>
        public static string SecondValueErrorMsg {
            get {
                return ResourceManager.GetString("SecondValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz szczegóły.
        /// </summary>
        public static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz rodzaj funkcji.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa modelu.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jest wymagana.
        /// </summary>
        public static string SystemNameErrorMsg {
            get {
                return ResourceManager.GetString("SystemNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trzeci punkt.
        /// </summary>
        public static string ThirdValue {
            get {
                return ResourceManager.GetString("ThirdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj trzecią charakterystyczną wartość.
        /// </summary>
        public static string ThirdValueErrorMsg {
            get {
                return ResourceManager.GetString("ThirdValueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapezowa.
        /// </summary>
        public static string Trapezoid {
            get {
                return ResourceManager.GetString("Trapezoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trójkątna.
        /// </summary>
        public static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz rodzaj funkcji przynależności.
        /// </summary>
        public static string TypeErrorMsg {
            get {
                return ResourceManager.GetString("TypeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykorzystaj do obliczeń.
        /// </summary>
        public static string UseModel {
            get {
                return ResourceManager.GetString("UseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę użytkownika.
        /// </summary>
        public static string UserNameErrorMsg {
            get {
                return ResourceManager.GetString("UserNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj hasło.
        /// </summary>
        public static string UserPasswordErrorMsg {
            get {
                return ResourceManager.GetString("UserPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj tego modelu.
        /// </summary>
        public static string UseThisModel {
            get {
                return ResourceManager.GetString("UseThisModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba funkcji przynależności.
        /// </summary>
        public static string VariableFunctionsNumber {
            get {
                return ResourceManager.GetString("VariableFunctionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa zmiennej.
        /// </summary>
        public static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wejść musi mieścić się w przedziale 1-10.
        /// </summary>
        public static string WrongInputsNumber {
            get {
                return ResourceManager.GetString("WrongInputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba funkcji musi być dodatnia.
        /// </summary>
        public static string WrongMFNumber {
            get {
                return ResourceManager.GetString("WrongMFNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wyjść musi mieścić się w przedziale 1-10.
        /// </summary>
        public static string WrongOutputsNumber {
            get {
                return ResourceManager.GetString("WrongOutputsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba reguł musi mieścić się w przedziale 1-100.
        /// </summary>
        public static string WrongRulesNumber {
            get {
                return ResourceManager.GetString("WrongRulesNumber", resourceCulture);
            }
        }
    }
}
